CREATE TABLE PAIS
(
	ID_PAIS bigint(5) NOT NULL AUTO_INCREMENT,
	NOMBRE_PAIS VARCHAR(50) NULL,

PRIMARY KEY (ID_PAIS)
	
);


CREATE TABLE DEPARTAMENTO
(
	ID_DEPARTAMENTO bigint(8) NOT NULL AUTO_INCREMENT,
	NOMBRE_DEPARTAMENTO VARCHAR(50) NULL,
	ID_PAIS_DEPARTAMENTO bigint(8) NOT NULL,

	PRIMARY KEY (ID_DEPARTAMENTO)
);


CREATE TABLE CIUDAD
(
	ID_CIUDAD bigint(8) NOT NULL AUTO_INCREMENT,
	NOMBRE_CIUDAD VARCHAR(50) NULL,
	ID_DEPARTAMENTO_CIUDAD bigint(8) NOT NULL,

	PRIMARY KEY (ID_CIUDAD)
	
);

CREATE TABLE PERSONA
(
	ID_PERSONA bigint(10) NOT NULL AUTO_INCREMENT,
	NOMBRE_PERSONA VARCHAR(40) NULL,
	APELLIDO_PERSONA VARCHAR(40) NULL,
	FECHA_NACIMIENTO_PERSONA DATE NULL,
	NUMERO_IDENTIDAD_PERSONA VARCHAR(20) NULL,
	DIRECCION_RESIDENCIA_PERSONA TEXT NULL,
	EMAIL_PERSONA NVARCHAR(80) DEFAULT NULL,
	ID_CIUDAD_RESIDENCIA_PERSONA bigint(8) NOT NULL,
	ID_SEXO_PERSONA INT NULL,

	PRIMARY KEY (ID_PERSONA),
	UNIQUE (NUMERO_IDENTIDAD_PERSONA)

);


CREATE TABLE SEXO
(
	ID_SEXO INT NOT NULL,  
	SEXO VARCHAR(20) NULL,
	
	PRIMARY KEY (ID_SEXO)
);

CREATE TABLE TIPO_TELEFONO
(
	ID_TIPO_TELEFONO INT NOT NULL,
	TIPO_TELEFONO VARCHAR(30) NULL,
	DESCRIPCION_TIPO_TELEFONO TEXT NULL,

	PRIMARY KEY (ID_TIPO_TELEFONO)
);


CREATE TABLE TELEFONO
(
	ID_TELEFONO INT NOT NULL,
	TELEFONO VARCHAR(20) NULL,
	ID_TIPO_TELEFONO INT NULL,
	ID_PERSONA_TELEFONO bigint(10) NOT NULL,

	CONSTRAINT PK_ID_TELEFONO PRIMARY KEY (ID_TELEFONO),
	UNIQUE (TELEFONO)
);


ALTER TABLE DEPARTAMENTO ADD 
	CONSTRAINT FK_ID_PAIS_DEPARTAMENTO FOREIGN KEY (ID_PAIS_DEPARTAMENTO) REFERENCES PAIS(ID_PAIS);


ALTER TABLE CIUDAD ADD 
	CONSTRAINT FK_ID_DEPARTAMENTO_CIUDAD FOREIGN KEY (ID_DEPARTAMENTO_CIUDAD) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO);


ALTER TABLE PERSONA ADD (
	CONSTRAINT FK_ID_CIUDAD_RESIDENCIA_PERSONA FOREIGN KEY (ID_CIUDAD_RESIDENCIA_PERSONA) REFERENCES CIUDAD(ID_CIUDAD),
	CONSTRAINT FK_ID_SEXO_PERSONA FOREIGN KEY (ID_SEXO_PERSONA) REFERENCES SEXO(ID_SEXO));

ALTER TABLE TELEFONO ADD(
	CONSTRAINT FK_ID_TIPO_TELEFONO FOREIGN KEY (ID_TIPO_TELEFONO) REFERENCES TIPO_TELEFONO(ID_TIPO_TELEFONO),
	CONSTRAINT FK_ID_PERSONA_TELEFONO FOREIGN KEY (ID_PERSONA_TELEFONO) REFERENCES PERSONA(ID_PERSONA));