CREATE TABLE CLIENTE
(
	ID_CLIENTE bigint(10) NOT NULL AUTO_INCREMENT,
	ID_PERSONA_CLIENTE bigint(10) NOT NULL,

	PRIMARY KEY (ID_CLIENTE),
	UNIQUE (ID_PERSONA_CLIENTE)
);

ALTER TABLE CLIENTE ADD
	CONSTRAINT FK_ID_PERSONA_CLIENTE FOREIGN KEY (ID_PERSONA_CLIENTE) REFERENCES PERSONA(ID_PERSONA);